# This configures fully synthetic data generation.
# A series of actions are defined by the sequence of targets that the arm should move towards
# The letter targets and their locations are defined in another file, this only captures behaviors

# The sequence of letters to move to
#sequence: ['A', 'I', 'B', 'H']
sequence: ['random', 'A', 'random', 'H', 'random', 'B', 'random', 'I']
repeats: 50
# 0.5cm stddev noise in the placement in all dimensions, z is offset by 3cm so the arm doesn't go too low.
target_offsets: [0., 0., 0.03]
target_noise: [0.0, 0.0, 0.0]
#target_noise: [0.0, 0.0, 0.0]

# Arm config
arm_start: [0.25, 0.0, 0.03]
r_range: [0.15, 0.35]
t_range: [-0.15, 0.15]
z_range: [0.02, 0.10]
