# Servo locations for a "0" position. Because the connection from the elbow to the shoulder is made
# in two pieces, in order to get the elbow joint to be directly above the shoulder joint they are
# both slightly bent.
waist:         0.0
shoulder:      -0.40
elbow:         0.27
wrist_angle:   -0.07
wrist_rotate:  0.0
gripper:       1.2808740139007568
left_finger:   0.03707965835928917
right_finger:  -0.03707965835928917
